### ISSUE TITLE
s4 panics on some .etl files

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/super-speedy-syslog-searcher#105]
## Summary

`s4.exe` panics when processing `.etl` files.

### Current behavior

```text
PS> $env:RUST_BACKTRACE="full"

PS> s4.exe "C:\Windows\Logs\WindowsUpdate\WindowsUpdate.20230422.214724.988.1.etl"
thread 'WindowsUpdate.20230422.214724.988.1.etl' panicked at 'BlockReader::new bad filetype Unknown', C:\Users\user1\cargo\registry\src\github.com-1ecc6299db9ec823\super_speedy_syslog_searcher-0.6.60\src\readers\blockreader.rs:1186:17
stack backtrace:
   0:     0x7ff7fe6d71b2 - <unknown>
   1:     0x7ff7fe6f0c7b - <unknown>
   2:     0x7ff7fe6d2fea - <unknown>
   3:     0x7ff7fe6d6efb - <unknown>
   4:     0x7ff7fe6d9549 - <unknown>
   5:     0x7ff7fe6d91cb - <unknown>
   6:     0x7ff7fe6d9de0 - <unknown>
   7:     0x7ff7fe6d9b6e - <unknown>
   8:     0x7ff7fe6d7bcf - <unknown>
   9:     0x7ff7fe6d9820 - <unknown>
  10:     0x7ff7fe701fd5 - <unknown>
  11:     0x7ff7fe5a5bf0 - <unknown>
  12:     0x7ff7fe5b921e - <unknown>
  13:     0x7ff7fe5be5b1 - <unknown>
  14:     0x7ff7fe5c77de - <unknown>
  15:     0x7ff7fe54290c - <unknown>
  16:     0x7ff7fe529aae - <unknown>
  17:     0x7ff7fe52a3d8 - <unknown>
  18:     0x7ff7fe6dee0c - <unknown>
  19:     0x7ff97104269d - BaseThreadInitThunk
  20:     0x7ff972caa9f8 - RtlUserThreadStart
```

This occurred for several different `.etl` files.

`file` reports

```
$ file "WindowsUpdate.20230422.214724.988.1.etl"
WindowsUpdate.20230422.214724.988.1.etl: Windows Event Trace Log "C:\Windows\Logs\WindowsUpdate\WindowsUpdate.20230422.214724.988.1.etl"
```

### Other

At one time this worked.

You can see `.etl` files with

```text
PS> get-childitem -File -Filter '*.etl' -Recurse -Path "C:\Windows\Logs" | Select -Property fullname
```

**Comment by jtmoon79** [comment]
Debug build run under Ubuntu looks like

```
$ RUST_BACKTRACE=1 ./target/debug/s4 "/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl"
                →exec_syslogprocessor: ("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl")
        →processing_loop::recv_many_chan: (…)
                    ↔SyslogProcessor::new: ("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl", Unknown, 65535, -07:00)
         processing_loop::recv_many_chan: select.recv(Receiver { .. });
                        ↔SyslineReader::new: ("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl", Unknown, 65535, -07:00)
         processing_loop::recv_many_chan: map_index_pathid: {0: 0}
                            ↔LineReader::new: ("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl", Unknown, 65535)
                                →BlockReader::new: ("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl", Unknown, 65535)
                                 BlockReader::new: open_options.read(true).open("/mnt/c/Windows/Logs/WindowsUpdate/WindowsUpdate.20230422.214724.988.1.etl")
thread 'WindowsUpdate.20230422.214724.988.1.etl' panicked at 'BlockReader::new bad filetype Unknown', src/readers/blockreader.rs:1186:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: s4lib::readers::blockreader::BlockReader::new
             at ./src/readers/blockreader.rs:1186:17
   3: s4lib::readers::linereader::LineReader::new
             at ./src/readers/linereader.rs:209:27
   4: s4lib::readers::syslinereader::SyslineReader::new
             at ./src/readers/syslinereader.rs:450:24
   5: s4lib::readers::syslogprocessor::SyslogProcessor::new
             at ./src/readers/syslogprocessor.rs:292:29
   6: s4::exec_syslogprocessor
             at ./src/bin/bin.rs:1614:32
   7: s4::exec_fileprocessor_thread
             at ./src/bin/bin.rs:2255:14
   8: s4::processing_loop::{{closure}}
             at ./src/bin/bin.rs:3088:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
