### ISSUE TITLE
s4 crash on zero byte /var/log/btmp --summary

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/super-speedy-syslog-searcher#69]
The following command crashes

```text
$ RUST_BACKTRACE=1 s4 /var/log/btmp  -s

Files:

File: /var/log/btmp (TEXT) MimeGuess([])
  Summary Processed:
thread 'main' panicked at 'Unsupported filetype FileUnset', /home/user1/.cargo/registry/src/github.com-1ecc6299db9ec823/super_speedy_syslog_searcher-0.1.43/src/bin/bin.rs:2486:21
```

File `btmp` is

```
$ ls -l /var/log/btmp
-rw-rw---- 1 root utmp 0 Aug 19  2021 /var/log/btmp
```

Using s4 version 0.1.43.

This causes a crash whenever there is `--summary` and a file named `btmp`.

**Comment by jtmoon79** [comment]
Relates to #70

**Comment by jtmoon79** [comment]
Oddly, I cannot reproduce the error in a local clean project build. Using either debug or release builds.

```text
$ touch /tmp/btmp
$ RUST_BACKTRACE=1 ./target/release/s4 /tmp/btmp  -s
...
(no failure)
```

**Comment by jtmoon79** [comment]
Ah, this is due to a file permissions mode not allowing some file read done during --summary.

Run `s4` as a non-root user.

```text
$ touch /tmp/btmp
$ chmod 0000 /tmp/btmp
$ sudo -u nobody -- ./target/release/s4 /tmp/btmp -s

Files:

File: /tmp/btmp (TEXT) MimeGuess([])
  Summary Processed:
thread 'main' panicked at 'Unsupported filetype FileUnset', /home/user1/.cargo/registry/src/github.com-1ecc6299db9ec823/super_speedy_syslog_searcher-0.1.43/src/bin/bin.rs:2486:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
